import Meals from "@/components/Meals";
import styles from "./styles.module.css"
import { Headland_One } from 'next/font/google'

const headland = Headland_One({weight: ['400'], subsets: ['latin']})

// amader tab er upore title show korbe aitar maddhoem, jeita amra react helmet use kore kortam.
export const metadata = {
    title: "Meals",
    description: "Generated by create next app",
};



const page = () => {

    return (
        <div className="mt-11 ml-11">
            <h1 className={styles.text_tomato}>Chose Your Meals</h1>
            <p className={`${headland.className}`}>Lorem ipsum dolor sit amet consectetur adipisicing elit. In quam cumque dolorem. Minima ea at mollitia pariatur, harum dolorem voluptatibus!</p>
            <Meals></Meals>
        </div>
    );
};

export default page;